#! /bin/sh

GIT_DIR=`git rev-parse --git-dir`
HOOKS_DIR="${GIT_DIR}/hooks"

# echo "GIT_DIR=$GIT_DIR"
# echo "HOOKS_DIR=${HOOKS_DIR}"

source "${HOOKS_DIR}/common.sh"

isOnMasterBranch
if [ $? -eq 0 ]; then
    echo "can't commit on master branch."
    echo "please commit on topic branch."
    exit 1
fi

exit 0
